### ISSUE TITLE
uniapp 上中下布局外部的滚动条

### ISSUE THREAD

**Issue by ycjqf** [ycjqf/ycjqf.github.io#1]
```scss
// uni.scss
uni-page-body,html,body {
	height: 100%;
	box-sizing: border-box;
}
// PAGE
.page {
	height: 100%;
	display: flex;
	flex-direction: column;
	flex-wrap: wrap;
	overflow: hidden;
}
```
